package sampling

import org.apache.spark.rdd.RDD
import org.apache.spark.sql.DataFrame

class Tables {
  var lineitem: DataFrame = _
  var customer: DataFrame = _
  var orders  : DataFrame = _
  var supplier: DataFrame = _
  var nation  : DataFrame = _
  var region  : DataFrame = _

  // The samples generated by the sampler
  var samples : List[RDD[_]] = _

  // target error [0, 1]
  var e : Double = _
  // target confidence level [0, 1]
  var ci: Double = _
}
